from ctypes import *
a = c_int()
b = c_long(0)
c = c_char_p(b"Hello world!")
d = c_ushort(-5)
e = c_ushort(65531)
f = c_char_p(b'loves python')
seitz = c_char_p(b"loves python")
print(a.value)
print(b.value)
print(c.value)
print(d.value)
print(e.value)
print(f.value)
print(seitz)
print(seitz.value)